services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-ai
    ports:
      - "5433:5432" # Alterando para 5433 na máquina local
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
